version: "3.9"
services:
  postgres_register:
    container_name: postgres_register
    image: postgres:latest
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - '5432:5432'
  postgres_marketplace:
    container_name: postgres_marketplace
    image: postgres:latest
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - '5433:5432'
  keycloak_delivery:
    container_name: keycloak_delivery
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_delivery:
    container_name: jaeger_delivery
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  prometheus_delivery:
    container_name: prometheus_delivery
    image: prometheus-delivery
    network_mode: "host"
  grafana_delivery:
    container_name: grafana_delivery
    image: grafana/grafana:latest
    network_mode: "host"
  artemis_delivery:
    container_name: artemis_delivery
    image: artemis-adoptopenjdk-11:latest
    network_mode: "host"
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
  mongodb_delivery:
    container_name: mongodb_delivery
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  zookeeper:
    container_name: zookeeper_container
    image: zookeeper:latest
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    container_name: kafka_container
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka
  elastic:
    container_name: elaticsearch
    image: elasticsearch:7.17.3
    network_mode: "host"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana
    image: kibana:7.17.3
    network_mode: "host"
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200

  logstash:
    container_name: logstash
    image: logstash:7.17.3
    volumes:
      - source: ./pipelines
        target: /usr/share/logstash/pipeline
    network_mode: "host"
    depends_on:
      - elastic