version: "3.9"
services:
  postgres_register:
    container_name: postgres_register
    image: postgres:latest
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - '5432:5432'
  keycloak_delivery:
    container_name: keycloak_delivery
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"